const PRODUCTION_NAME = 'Pinnacle OA'
const COLOR_PRODUCTION = '#00D4FF'
const COLOR_BACKGROUND = '#D8D8D8'
const COLOR_FONT_MAIN = '#4D4D4D'
const COLOR_FONT_SECONDARY = '#9E9E9E'
const SIZE_ICON_XS = '16px'
const SIZE_ICON_SM = '20px'
const SIZE_ICON_MD = '24px'
const SIZE_ICON_LG = '32px'
const SIZE_ICON_XL = '64px'

export {
    PRODUCTION_NAME,
    COLOR_PRODUCTION,
    COLOR_BACKGROUND,
    COLOR_FONT_MAIN,
    COLOR_FONT_SECONDARY,
    SIZE_ICON_XS,
    SIZE_ICON_SM,
    SIZE_ICON_MD,
    SIZE_ICON_LG,
    SIZE_ICON_XL
}
